### ISSUE TITLE
Why the dependency must be python3.7

### ISSUE THREAD

**Issue by wongqingbin** [bauerji/flask_pydantic#10]
Why the dependency must be python3.7
I want to use python3.6

**Comment by bauerji** [comment]
Hi,

From the top of my head I know I am using `dataclasses` module which isn't part of standard library in `3.6`. However it can be backported using [dataclasses library](https://pypi.org/project/dataclasses/).

With upcoming release of `3.8` (which is expected on Monday, 2020-10-05) in mind don't You think about upgrading?

Jirka

**Comment by bauerji** [comment]
I added support for python version `3.6`. It's released in package version `0.2.0`.

If you aren't satisfied with my solution feel free to reopen this issue or create a new one.

Jirka
