### ISSUE TITLE
Is there a way to convert key casing in responses?

### ISSUE THREAD

**Issue by eboddington** [bauerji/flask_pydantic#14]
I'd like to have my Pydantic models defined in `snake_case` but have the API return JSON with `camelCase` fields.

In FastAPI, I can do the following:
```
def to_camel(string: str):
    # returns "string" converted to camelCase

class MyModel(BaseModel):
    foo_bar: str

    class Config:
        alias_generator = to_camel
        allow_population_by_field_name = True
```

And the resulting JSON will be `{"fooBar": "x"}`. This is similar to the way it's described in the [Pydantic docs](https://pydantic-docs.helpmanual.io/usage/model_config/#alias-generator).

This doesn't work with flask-pydantic. Is there any way to achieve similar behaviour?

**Comment by bauerji** [comment]
Hi, 

please refer to #15 where I implemented the solution.

Jirka

**Comment by bauerji** [comment]
Model aliases for response models are added in newest version `0.4.0`.

If you are not satisfied with solution or have another suggestion, please reopen this or create a new issue.

Jirka

**Comment by eboddington** [comment]
Thanks for the super quick fix, it's working well!
