### ISSUE TITLE
Validation for Array of Models fails

### ISSUE THREAD

**Issue by ckwojai** [bauerji/flask_pydantic#20]
```
from typing import List
from flask_pydantic import validate

api = Blueprint("lineage-collector", __name__)

class EntityPayload(BaseModel):
    attributes: dict
    typeName: str

class EntityPayloadBulk(BaseModel):
    __root__:  List[EntityPayload]

@api.route('/entity/bulk', methods=["POST"])
@validate()
def entity_bulk(body: EntityPayloadBulk):
    return "Hello World"

```
Call to this endpoint returns the following error:

> `  File &quot;/usr/local/lib/python3.9/site-packages/flask_pydantic/core.py&quot;, line 158, in wrapper
>     b = body_model(**body_params)
> TypeError: api.routes.EntityPayloadBulk() argument after ** must be a mapping, not list
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File &quot;/usr/local/lib/python3.9/site-packages/flask/app.py&quot;, line 2464, in __call__
>     return self.wsgi_app(environ, start_response)
>   File &quot;/usr/local/lib/python3.9/site-packages/flask/app.py&quot;, line 2450, in wsgi_app
>     response = self.handle_exception(e)
>   File &quot;/usr/local/lib/python3.9/site-packages/flask/app.py&quot;, line 1867, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File &quot;/usr/local/lib/python3.9/site-packages/flask/_compat.py&quot;, line 39, in reraise
>     raise value
>   File &quot;/usr/local/lib/python3.9/site-packages/flask/app.py&quot;, line 2447, in wsgi_app
>     response = self.full_dispatch_request()
>   File &quot;/usr/local/lib/python3.9/site-packages/flask/app.py&quot;, line 1952, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File &quot;/usr/local/lib/python3.9/site-packages/flask/app.py&quot;, line 1821, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File &quot;/usr/local/lib/python3.9/site-packages/flask/_compat.py&quot;, line 39, in reraise
>     raise value
>   File &quot;/usr/local/lib/python3.9/site-packages/flask/app.py&quot;, line 1950, in full_dispatch_request
>     rv = self.dispatch_request()
>   File &quot;/usr/local/lib/python3.9/site-packages/flask/app.py&quot;, line 1936, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File &quot;/usr/local/lib/python3.9/site-packages/flask_pydantic/core.py&quot;, line 164, in wrapper
>     raise JsonBodyParsingError()
> flask_pydantic.exceptions.JsonBodyParsingError`

**Comment by bauerji** [comment]
Hi,

Thank you for pointing out. To be honest I did not know about pydantic's [custom root types](https://pydantic-docs.helpmanual.io/usage/models/#custom-root-types) using `__root__` attribute. I will modify functionality to take care of them.

Jirka

**Comment by bauerji** [comment]
I added this feature to support as many pydantic's feature as possible.

However I strongly encourage you not to use custom root types.

The preferred way of achieving the same result is using `validate's` `request_body_many` attribute
```
from typing import List
from flask_pydantic import validate

api = Blueprint("lineage-collector", __name__)

class EntityPayload(BaseModel):
    attributes: dict
    typeName: str

@api.route('/entity/bulk', methods=["POST"])
@validate(request_body_many=True)
def entity_bulk(body: EntityPayload):
    return "Hello World"
```

**Comment by pdeep95** [comment]
I think using List[EntityPayload] will be better, like

`def entity_bulk(body: List[EntityPayload]):`

By using `request_body_many=True` we get an array of EntityPayload in body, not an object of EntityPayload. This messes up autocomplete in IDEs.
