### ISSUE TITLE
Request change: the example in the main README.md file is not clear

### ISSUE THREAD

**Issue by OmarThinks** [bauerji/flask_pydantic#21]
Before I start, I really thank you so much for this package.
_____________
I request to make a change:
The example at the README.md file in the main page of the package is not clear.
At first, I thought that the package was not working correctly.
I kept working, and sending requests till finally worked after about 15 minutes of trying.
____
For this reason:
The example is very advanced, and for someone who wanna learn the package for the first time, the learning curve of the example is very hard to learn.
This is dangerous for someone who wants to learn about the package for the first time.
_____
So I would like to solve this problem by doing this.
Create 3 separate endpoints:
1. To read the GET request only, and above it the pydantic class of it.
2. To read the JSON request body only, and above it the pydantic class of it.
3. To read both the JSON request and the GET request together, using the old pydantic classes.
______
If God willed, I can make this change.
I will make these changes, If you give the permission.
Thank you!

**Comment by bauerji** [comment]
Hello Omar,

feel free to modify README to give it more clarity and submit a PR. Any contribution is welcome!

Jirka

**Comment by OmarThinks** [comment]
Okay.
If God willed, I will do my best.
Thank you so much for giving me this opportunity.
👍 💯 🥇

**Comment by bauerji** [comment]
released in version `0.6.0`
