### ISSUE TITLE
Request change: passing the validated results to the route as parameters

### ISSUE THREAD

**Issue by OmarThinks** [bauerji/flask_pydantic#22]
# Request change: passing the validated results to the route as parameters

---

I can make this change.  
After the data have been validated by the decorator,  
Now the developer has to validate them again inside the route.

---

What if I could pass them after they have clean and validated into the route.  
They will be passed from the decorator to the route automatically.  
And the user will not have to validate them again in the route.
  
So the code will look like this:
```python
@app.route("/", methods=["POST"])
@validate(body=BodyModel, query=QueryModel)
def post(requested):
	#Requested is validated
	body = requested.body
	# This is body after validation
	query = requested.query
	# This is query after validation
	name = body["name"]
	nickname = body["nickname"]
	age = query["age"]
```
This is all what the developer will have to write.
Cleaner code.

---
If God willed, I can make this change.
I request your permission to make this change
Thank you!

**Comment by bauerji** [comment]
Hi Omar,

I do not quite know what you meant by _After the data have been validated by the decorator,
**Now the developer has to validate them again inside the route.**_

There are two ways of how to pass validated parameters into your route function. 

- when you use `validate()` decorator arguments then validated parameters are accessible via `request` variable

- using [validated function kwargs type hints](https://github.com/bauerji/flask_pydantic#using-the-decorated-function-kwargs) gives you direct access to these validated parameters.

I thing the latter one is what you are looking for.

Jirka

**Comment by OmarThinks** [comment]
Hi Jirka!
That was exactly what I have meant.
If God willed, When I update the README.md, I will make sure that this is very clear.
Because this is what exactly what I came here to this package looking for as a developer.
