### ISSUE TITLE
Pinned version of Pydantic

### ISSUE THREAD

**Issue by flipstone42** [bauerji/flask_pydantic#29]
Hi,

You appear to have pinned version `1.7.1` of Pydantic in [base.pip](https://github.com/bauerji/flask_pydantic/blob/master/requirements/base.pip). Would it be possible to remove this pinned version, or to change it to a minimum version? Thanks!

**Comment by bauerji** [comment]
Change is released in package version `0.6.3`. Feel free to reopen or create another issue if you're not satisfied with solution
