### ISSUE TITLE
Overriding http return stats on exception

### ISSUE THREAD

**Issue by jhoover4** [bauerji/flask_pydantic#6]
I notice that you can update the returned status on success, but can you do the same thing on error? We typically use `422`s instead of `400`s for malformed requests.

Thanks!

**Comment by bauerji** [comment]
Hi,

it is not possible yet. But I think this would be a good new feature. I will add the possibility to modify status code when `ValidationError` occurs using flask app config value `FLASK_PYDANTIC_VALIDATION_ERROR_STATUS_CODE`.

Does this solve your problem?

Jirka

**Comment by jhoover4** [comment]
Hey thanks for responding so quickly to this! I was thinking maybe something in the decorator itself? A config value like this could also work though

**Comment by bauerji** [comment]
Fine, it's released in version `0.0.7`. Feel free to reopen or create another issue if you wished to use more adjustable way (such as decorator parameter etc.)

**Comment by jhoover4** [comment]
Okay I'll see if this works for now. Thank you!
